global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"] # if FastAPI runs locally on 8000
